runtime:
  environment: tslib

model:
  d_model: 64
  n_heads: 4
  d_ff: 128
  e_layers: 2
  d_layers: 1
  moving_avg: 25
  dropout: 0.1
  activation: gelu
  embed: timeF
  freq: t
  version: fourier
  mode_select: random
  modes: 32
