runtime:
  environment: tslib

model:
  d_model: 64
  n_heads: 4
  d_ff: 128
  e_layers: 2
  d_layers: 1
  factor: 1
  dropout: 0.1
  activation: gelu
  embed: timeF
  freq: t
  label_len: 48
  distil: true
