"""Generate the checked-in command reference from the unified parser."""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Any

from _bootstrap import ROOT  # noqa: F401  (bootstraps src/ on direct execution)
from cli.command_schema import (
    PUBLIC_OVERRIDE_BY_DEST,
    build_parser,
    build_reference_parser,
)


OUTPUT_PATH = ROOT / "docs" / "COMMAND_REFERENCE.md"


_EXAMPLES = {
    "train": """```powershell
python scripts\\run.py train `
  --model node_shared_lstm dlinear patchtst `
  --run-id benchmark_seed2026 `
  --device cuda
```""",
    "evaluate": """```powershell
python scripts\\run.py evaluate `
  --model node_shared_lstm `
  --run-id node_shared_lstm_eval `
  --device cuda `
  --checkpoint results\\node_shared_lstm\\node_shared_lstm_seed2026\\best.pt
```""",
    "check": """```powershell
python scripts\\run.py check `
  --model node_shared_lstm `
  --device cuda `
  --full-shape `
  --batch-size 4
```""",
    "preflight": """```powershell
python scripts\\run.py preflight `
  --model node_shared_lstm `
  --device cuda `
  --batch-size 4
```""",
    "repeatability": """```powershell
python scripts\\run.py repeatability `
  --model node_shared_lstm `
  --run-id repeatability_seed2026 `
  --device cuda `
  --prediction-atol 1e-6
```""",
}


def _subparsers(parser):
    return next(
        action
        for action in parser._actions
        if action.__class__.__name__ == "_SubParsersAction"
    )


def _group_titles(parser) -> dict[int, str]:
    titles: dict[int, str] = {}
    for group in parser._action_groups:
        for action in group._group_actions:
            titles[id(action)] = group.title
    return titles


def _type_name(action) -> str:
    spec = PUBLIC_OVERRIDE_BY_DEST.get(action.dest)
    if spec is not None:
        base = spec.value_type
    elif action.type is None:
        base = "flag" if action.nargs == 0 else "str"
    elif action.type is Path:
        base = "path"
    else:
        base = getattr(action.type, "__name__", str(action.type))
    return f"list[{base}]" if action.nargs in {"+", "*"} else base


def _default_text(action) -> str:
    spec = PUBLIC_OVERRIDE_BY_DEST.get(action.dest)
    if spec is not None:
        return "未提供：继承 configs/experiment.yaml"
    if action.default is None:
        return "无"
    if action.default is False and action.nargs == 0:
        return "未提供时关闭"
    if isinstance(action.default, Path):
        return str(action.default)
    return repr(action.default)


def _yaml_path(action) -> str:
    spec = PUBLIC_OVERRIDE_BY_DEST.get(action.dest)
    return "; ".join(".".join(path) for path in spec.yaml_paths) if spec is not None else "—"


def _action_row(action, group_title: str) -> str:
    options = ", ".join(action.option_strings) or action.dest
    required = "是" if action.required else "否"
    public = "是" if action.dest in PUBLIC_OVERRIDE_BY_DEST else "否"
    help_text = " ".join((action.help or "").split()).replace("|", "\\|")
    return (
        f"| `{options}` | {group_title} | {required} | {_type_name(action)} | "
        f"{_default_text(action)} | `{_yaml_path(action)}` | {public} | {help_text} |"
    )


def render_reference() -> str:
    parser = build_parser()
    subparsers = _subparsers(parser)
    lines = [
        "# Command Reference",
        "",
        "<!-- Generated by scripts/generate_command_reference.py; do not edit manually. -->",
        "",
        "所有任务统一从 `scripts/run.py` 执行，参数定义来自 `src/cli/command_schema.py`。",
        "",
        "## 覆盖优先级",
        "",
        "```text",
        "内置结构默认 < configs/experiment.yaml < 命令行显式覆盖",
        "```",
        "",
        "未提供公共实验参数时，使用 `configs/experiment.yaml` 的值；显式提供的值只影响本次运行。模型配置遵循 `runtime`/`model` 结构：",
        "",
        "```text",
        "configs/models/<model>.yaml: runtime.environment + model 参数",
        "```",
        "",
        "训练或评估结果目录至少包含 `resolved_config.yaml`、`cli_overrides.yaml` 和 `command.json`；调度器按模型 YAML 选择环境，每个模型由独立 Python 子进程运行。",
        "",
        "## 实时帮助",
        "",
        "```powershell",
        "python scripts\\run.py --help",
        "python scripts\\run.py <command> --help",
        "```",
        "",
    ]
    for command, command_parser in subparsers.choices.items():
        lines.extend([f"## `{command}`", "", command_parser.description or "", ""])
        lines.extend(["### 参数", "", "| 参数 | 分组 | 必填 | 类型 | 默认行为 | YAML 字段 | 公共覆盖 | 说明 |", "|---|---|---:|---|---|---|---:|---|"])
        groups = _group_titles(command_parser)
        for action in command_parser._actions:
            if not action.option_strings or action.dest == "help":
                continue
            lines.append(_action_row(action, groups.get(id(action), "参数")))
        lines.extend(["", "### 示例", "", _EXAMPLES[command], ""])
    lines.extend(
        [
            "## 覆盖记录",
            "",
            "`resolved_config.yaml` 是公共 YAML 应用命令行覆盖后的完整最终配置；`cli_overrides.yaml` 只保存本次实际提供的覆盖项；`command.json` 保存原始 argv、命令、模型和配置路径。",
            "",
            "```text",
            "YAML 默认值 + 命令行显式覆盖 = 本次 resolved config",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = build_reference_parser().parse_args(sys.argv[1:] if argv is None else argv)
    rendered = render_reference()
    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"missing generated reference: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"command reference is out of date: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        print(f"command reference is up to date: {OUTPUT_PATH}")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"generated: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
